// Derive the second Baby Jubjub generator H (unknown discrete log w.r.t. G = Base8) by
// hash-to-curve on a fixed tag, cofactor-cleared into the prime-order subgroup. Writes
// transfer/generators.circom and lib/generators.json. Deterministic; run once, commit output.
import { buildBabyjub } from "circomlibjs";
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";

const bj = await buildBabyjub();
const F = bj.F;
const TAG = "pulse-privacy/babyjubjub/H/v1";

// twisted Edwards: A x^2 + y^2 = 1 + D x^2 y^2  =>  y^2 = (1 - A x^2) / (1 - D x^2)
function pointFromX(x) {
  const x2 = F.square(x);
  const num = F.sub(F.one, F.mul(bj.A, x2));
  const den = F.sub(F.one, F.mul(bj.D, x2));
  const y2 = F.div(num, den);
  const y = F.sqrt(y2);
  if (y === null || y === undefined) return null;
  return [x, y];
}

let H = null;
for (let ctr = 0; ctr < 1000 && !H; ctr++) {
  const h = createHash("sha256").update(`${TAG}:${ctr}`).digest();
  const x = F.e(BigInt("0x" + h.toString("hex")) % F.p);
  const p = pointFromX(x);
  if (!p || !bj.inCurve(p)) continue;
  // cofactor 8 clearing
  const q = bj.mulPointEscalar(p, 8n);
  if (bj.inSubgroup(q) && !F.isZero(q[0])) H = q;
}
if (!H) throw new Error("no H found");
const hx = F.toObject(H[0]), hy = F.toObject(H[1]);
const gx = F.toObject(bj.Base8[0]), gy = F.toObject(bj.Base8[1]);
console.log("G =", gx.toString(), gy.toString());
console.log("H =", hx.toString(), hy.toString());

writeFileSync(
  "transfer/generators.circom",
  `pragma circom 2.1.0;
// GENERATED by scripts/gen-h.mjs — do not edit.
// G = circomlib Base8 (prime-order subgroup generator). H = hash-to-curve("${TAG}"), cofactor-cleared.
function GEN_G() { return [${gx}, ${gy}]; }
function GEN_H() { return [${hx}, ${hy}]; }
`
);
writeFileSync(
  "lib/generators.json",
  JSON.stringify({ tag: TAG, G: [gx.toString(), gy.toString()], H: [hx.toString(), hy.toString()] }, null, 2) + "\n"
);
console.log("wrote transfer/generators.circom, lib/generators.json");
